import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getAllPokemons } from '@/hooks/api/pokemon.api'
import { SetPokemonState } from '@/lib/set-pokemon-state'
import { Navbar } from '@/components/Navbar'

export const metadata: Metadata = {
  title: 'CookUnity Challenge',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const pokemons = await getAllPokemons()

  return (
    <html lang="en">
      <body className="h-full">
        <SetPokemonState pokemonsData={pokemons} />
        <Navbar />
        {children}
      </body>
    </html>
  )
}
